### ISSUE TITLE
Usage of functions from other themes

### ISSUE THREAD

**Issue by JakobMiksch** [osm2pgsql-dev/osm2pgsql-themepark#19]
I wrote a custom theme using themepark: https://github.com/JakobMiksch/osm-feature-info/tree/d2c00d2/import-theme/osm-feature-info

there is the function `has_area_tags` the `basic` theme that I would like to reuse: https://github.com/osm2pgsql-dev/osm2pgsql-themepark/blob/23cc7ff/themes/basic/init.lua#L98-L121 Currently I have my own copy of the function in my theme which is redundant.

Is it possible to use functions from other themes?

**Comment by joto** [comment]
You should be able to access any "public" functions on a theme like this:

```
themepark.themes[THEME].FUNC
```

So in your case:

```
themepark.themes['basic'].has_area_tags(tags)
```

**Comment by JakobMiksch** [comment]
This works, but I have to init the external theme before:

```lua
themepark:init_theme('basic')
local has_area_tags = themepark.themes['basic'].has_area_tags
```

**Comment by JakobMiksch** [comment]
here the file where I use function: https://github.com/JakobMiksch/osm-feature-info/blob/b555b47fa559cfa1b74024dc08e252f214fc26f5/import-theme/osm-feature-info/topics/geography_tables.lua#L3-L5
