### ISSUE TITLE
Setting search dirs for themes with an evironment variable

### ISSUE THREAD

**Issue by lonvia** [osm2pgsql-dev/osm2pgsql-themepark#21]
themepark already has a function `add_theme_dir()` to add the location of an external theme. That's great when using a private theme that comes with a config file.

There is another use case where you want to use a third-party theme in your configuration that may be installed at a custom location. In such a case it would be preferable to hand in theme directories via an environment variable instead of hard-coding paths in the scripts.

**Comment by joto** [comment]
The envorinment variable THEMEPARK_PATH was added in e4c03baf5fea717b756089cd52d31b077890d64f.
