### ISSUE TITLE
Tilekiln config generation fails if directory not already created

### ISSUE THREAD

**Issue by pnorman** [osm2pgsql-dev/osm2pgsql-themepark#4]
When I uncommented the `themepark:plugin('tilekiln'):write_config('tk')` line from shortbread_v1_gen and ran `LUA_PATH="./osm2pgsql-themepark/lua/?.lua;;" osm2pgsql -d flex -O flex -S ./osm2pgsql-themepark/config/shortbread_gen.lua osm-data.pbf` I got an error:

2024-01-19 17:00:55  ERROR: Error loading lua config: ./osm2pgsql-themepark/lua/themepark/plugins/tilekiln.lua:73: Could open 'tk/ocean.10-14.sql.jinja2': tk/ocean.10-14.sql.jinja2: No such file or directory.

Upon examination I found that the issue was the `tk` directory did not exist, and it went away when I pre-created it.

**Comment by joto** [comment]
There is no builtin way in Lua to create a directory. I didn't want to add a dependency just for that. I have amended the README no mention that you need to create that directory.
